.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace - Connect to and manage your codespaces


.SH SYNOPSIS
.PP
\fBgh codespace [flags]\fP


.SH DESCRIPTION
.PP
Connect to and manage your codespaces


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh(1)\fP, \fBgh-codespace-code(1)\fP, \fBgh-codespace-cp(1)\fP, \fBgh-codespace-create(1)\fP, \fBgh-codespace-delete(1)\fP, \fBgh-codespace-list(1)\fP, \fBgh-codespace-logs(1)\fP, \fBgh-codespace-ports(1)\fP, \fBgh-codespace-ssh(1)\fP, \fBgh-codespace-stop(1)\fP
