.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-logs - Access codespace logs


.SH SYNOPSIS
.PP
\fBgh codespace logs [flags]\fP


.SH DESCRIPTION
.PP
Access codespace logs


.SH OPTIONS
.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace

.PP
\fB-f\fP, \fB--follow\fP[=false]
	Tail and follow the logs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fP
