.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-stop - Stop a running codespace


.SH SYNOPSIS
.PP
\fBgh codespace stop [flags]\fP


.SH DESCRIPTION
.PP
Stop a running codespace


.SH OPTIONS
.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fP
