.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-ports-forward - Forward ports


.SH SYNOPSIS
.PP
\fBgh codespace ports forward :\&... [flags]\fP


.SH DESCRIPTION
.PP
Forward ports


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace

.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace-ports(1)\fP
