.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-create - Create a codespace


.SH SYNOPSIS
.PP
\fBgh codespace create [flags]\fP


.SH DESCRIPTION
.PP
Create a codespace


.SH OPTIONS
.PP
\fB-b\fP, \fB--branch\fP=""
	repository branch

.PP
\fB-m\fP, \fB--machine\fP=""
	hardware specifications for the VM

.PP
\fB-r\fP, \fB--repo\fP=""
	repository name with owner: user/repo

.PP
\fB-s\fP, \fB--status\fP[=false]
	show status of post-create command and dotfiles


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fP
