.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-delete - Delete a codespace


.SH SYNOPSIS
.PP
\fBgh codespace delete [flags]\fP


.SH DESCRIPTION
.PP
Delete a codespace


.SH OPTIONS
.PP
\fB--all\fP[=false]
	Delete all codespaces

.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace

.PP
\fB--days\fP=0
	Delete codespaces older than \fB\fCN\fR days

.PP
\fB-f\fP, \fB--force\fP[=false]
	Skip confirmation for codespaces that contain unsaved changes

.PP
\fB-r\fP, \fB--repo\fP=""
	Delete codespaces for a \fB\fCrepository\fR


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fP
