.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-code - Open a codespace in Visual Studio Code


.SH SYNOPSIS
.PP
\fBgh codespace code [flags]\fP


.SH DESCRIPTION
.PP
Open a codespace in Visual Studio Code


.SH OPTIONS
.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace

.PP
\fB--insiders\fP[=false]
	Use the insiders version of Visual Studio Code


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-codespace(1)\fP
