.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-codespace-ports-visibility - Change the visibility of the forwarded port


.SH SYNOPSIS
.PP
\fBgh codespace ports visibility :{public|private|org}... [flags]\fP


.SH DESCRIPTION
.PP
Change the visibility of the forwarded port


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-c\fP, \fB--codespace\fP=""
	Name of the codespace

.PP
\fB--help\fP[=false]
	Show help for command


.SH EXAMPLE
.PP
.RS

.nf
gh codespace ports visibility 80:org 3000:private 8000:public

.fi
.RE


.SH SEE ALSO
.PP
\fBgh-codespace-ports(1)\fP
