.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-gpg-key-add - Add a GPG key to your GitHub account


.SH SYNOPSIS
.PP
\fBgh gpg-key add [] [flags]\fP


.SH DESCRIPTION
.PP
Add a GPG key to your GitHub account


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-gpg-key(1)\fP
