.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-repo-delete - Delete a repository


.SH SYNOPSIS
.PP
\fBgh repo delete  [flags]\fP


.SH DESCRIPTION
.PP
Delete a GitHub repository.

.PP
Deletion requires authorization with the "delete_repo" scope.
To authorize, run "gh auth refresh -s delete_repo"


.SH OPTIONS
.PP
\fB--confirm\fP[=false]
	confirm deletion without prompting


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-repo(1)\fP
