.nh
.TH "gh" "1" "Oct 2021" "" ""

.SH NAME
.PP
gh-repo-archive - Archive a repository


.SH SYNOPSIS
.PP
\fBgh repo archive \fP


.SH DESCRIPTION
.PP
Archive a GitHub repository.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh-repo(1)\fP
